var favCountries = ["Saudi Arabia", "Paris", "Turkey"];
var favCities = ["Islamabad", "Skardu", "Quetta"];
var FavLanguages = ["Arabix", "French", "Chineese"];
var FavColors = ["Blue", "Grey", "Purple"];
var FavDishes = ["Briyani", "Shami Kabab", "Nihari"];
console.log("My Favorite Countries which i want to visit are :", favCountries);
console.log("My Favorite Pakistani Cities are :", favCities);
console.log("My Favorite Languages which i want to learn are :", FavLanguages);
console.log("My Favorite Colors are:", FavColors);
console.log("My Favorite Dishes are:", FavDishes);
